import styles from './Email.module.scss';

interface HowToPlayProps {
    close(): void;
    visible: boolean;
}

function HowToPlay(props: HowToPlayProps) {
    const { close, visible } = props;
    
    return (
        <div
            className={styles.popupWrapper + (visible ? '' : (' ' + styles.hidden)) }
        >
            <div
                className={styles.backdrop}
                onClick={close}
            />
            <div className={styles.popup}>
                <div
                    className={styles.popupClose}
                    onClick={close}
                >
                    X
                </div>
                <div className={styles.popupBody}>
                    <p>
                        <strong>
                            Welcome to JustPhish
                        </strong>
                    </p>
                    <p>
                        Now that Twitter has changed its verification system, it's much harder to
                        identify which tweets are real and which contain disinformation. The
                        dangers of misinformation are huge, so we created this game to test how
                        good you are at identifying the lies.
                    </p>
                    <p>
                        You will be asked to enter a Twitter Handle (which can be anything you
                        like), and then the game will begin. In each round you will be presented
                        with one real tweet, which was actually posted by the account named, and
                        a fake tweet, which was generated by an AI that analysed the named
                        account's tweets. Some fake tweets will also contain AI generated images.
                        Drag the blue checkmark to the tweet that you believe is real.
                    </p>
                    <p>
                        For each correct answer, you will earn $8, which are your points. After
                        you fail four rounds, the game will end. If you did well enough, you may
                        reach the leaderboard.
                    </p>
                    <p>
                        You can begin by clicking outside of this popup, or clicking the X in the
                        top right corner. Please note that this game does not support mobile or
                        tablet devices.
                    </p>
                    <p>
                        Good luck!
                    </p>
                    <p>
                        <em>
                            Originally created within 24 hours by Liam Patterson, Nathan Taylor,
                            Sam Hirst & Will Newton for GreatUniHack 2022.
                        </em>
                    </p>
                    <p>
                        <em>
                            Later changes to make the game suitable for wider use made by Sam
                            Hirst.
                        </em>
                    </p>
                </div>
            </div>
        </div>
    );
}

export default HowToPlay;